# Generated by Django 5.1 on 2024-10-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_alter_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
