# Generated by Django 5.1.1 on 2024-12-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0006_rating_unique_user_food_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
