# Generated by Django 5.1.2 on 2024-10-27 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_food_image'),
        ('forum', '0002_post_user_thread_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.food'),
        ),
    ]
