# Generated by Django 5.1.2 on 2024-10-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_food_image'),
        ('forum', '0003_thread_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='food',
        ),
        migrations.AddField(
            model_name='thread',
            name='foods',
            field=models.ManyToManyField(blank=True, to='food.food'),
        ),
    ]
