# Generated by Django 5.1.2 on 2024-12-22 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('rating', '0001_initial'),
        ('tracker', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rated_foods',
            field=models.ManyToManyField(related_name='rated_foods', to='rating.rating'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tracked_foods',
            field=models.ManyToManyField(related_name='tracked_foods', to='tracker.tracker'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
