# Generated by Django 5.1 on 2024-10-25 13:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('rating', '0004_rating_user_alter_rating_id'),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rated_foods',
            field=models.ManyToManyField(related_name='rated_foods', to='rating.rating'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tracked_foods',
            field=models.ManyToManyField(related_name='tracked_foods', to='tracker.tracker'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
