# Generated by Django 5.1.2 on 2024-10-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('makanan', models.CharField(max_length=100)),
                ('lokasi', models.CharField(max_length=30)),
            ],
        ),
    ]
