# Generated by Django 5.1.2 on 2024-10-25 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        ('resto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resto',
            name='makanan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food.food'),
        ),
    ]
