# Generated by Django 5.1.1 on 2024-10-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.URLField(default='https://cdn1-production-images-kly.akamaized.net/jGwFeeZ3t6lUfdkz-S9BeFU6NnA=/469x625/smart/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/3463633/original/053964600_1621840903-bolu_pandan_panggang.jpg'),
        ),
    ]
