# Generated by Django 5.1.1 on 2024-10-27 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_tracker_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='restaurant',
        ),
    ]
