name: Push to PWS

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Force push to PWS
      env:
        PWS_URL: ${{ secrets.PWS_URL }}
      run: |
        git remote add pws $PWS_URL
        git fetch pws
        git reset --hard origin/main
        git push pws main:master --force